import ReduxProvider from "@/providers/ReduxProvider";
import "./globals.css";
import { ReactNode } from "react";
interface LayoutProps {
  children: ReactNode;
}

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps) {
  return (
    <html lang="en">
      <body className=" bg-[#FDFDFD] w-[100vw] h-[100vh]">
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}
